In [1]:
import pandas as pd

# Load dataset
df = pd.read_excel('/content/sample_data/ApexPlanet_DataAnalytics_Dataset.xlsx')

# Display first 5 rows
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [2]:
# Dataset information
df.info()

# Descriptive statistics
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
count,1000,1000,1000,1000,980.000000,1000,987,1000,1000,1000.000000,1000.000000,1000.000000
unique,992,342,947,425,NaN,2,8,6,5,NaN,NaN,NaN
top,ORD100050,2025-04-16,CUST2515,Customer_359,NaN,Male,Patna,Mobile,Electronics,NaN,NaN,NaN
freq,9,10,3,8,NaN,511,135,184,354,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,41.360204,NaN,NaN,NaN,NaN,5.435000,25486.783410,139399.439650
std,NaN,NaN,NaN,NaN,13.822597,NaN,NaN,NaN,NaN,2.838632,14179.402361,114100.051546
min,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,1.000000,145.780000,437.340000
25%,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,3.000000,13895.722500,47066.632500
50%,NaN,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,5.000000,25398.740000,108594.025000
75%,NaN,NaN,NaN,NaN,54.000000,NaN,NaN,NaN,NaN,8.000000,37512.382500,203722.882500
max,NaN,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,10.000000,49997.530000,493677.500000

In [3]:
# Remove duplicate rows
df = df.drop_duplicates()

# Fill missing values
df = df.fillna(method='ffill')

# Check if any missing values remain
print(df.isnull().sum())

Order_ID         0
Order_Date       0
Customer_ID      0
Customer_Name    0
Age              0
Gender           0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Total_Sales      0
dtype: int64

/tmp/ipykernel_700/2690054267.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')

In [4]:
# Save cleaned dataset
df.to_excel("Cleaned_Dataset.xlsx", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!